import { useEffect } from 'react';
import { ChevronLeft } from 'lucide-react';

export default function TermsPage() {
  useEffect(() => {
    document.title = 'Terms of Service — Kumpuni';
    const setMeta = (name: string, content: string, prop = false) => {
      const attr = prop ? 'property' : 'name';
      let el = document.querySelector(`meta[${attr}="${name}"]`);
      if (!el) {
        el = document.createElement('meta');
        el.setAttribute(attr, name);
        document.head.appendChild(el);
      }
      el.setAttribute('content', content);
    };
    setMeta('description', 'Kumpuni Terms of Service — read our terms for using the DIY home maintenance guide app.');
    setMeta('og:title', 'Terms of Service — Kumpuni', true);
    setMeta('og:description', 'Read the Kumpuni Terms of Service for the DIY home maintenance guide app.', true);
    setMeta('og:url', 'https://kumpuni.netlify.app/terms', true);
    setMeta('twitter:title', 'Terms of Service — Kumpuni');
    setMeta('twitter:description', 'Read the Kumpuni Terms of Service for the DIY home maintenance guide app.');
    const canonical = document.querySelector('link[rel="canonical"]');
    if (canonical) canonical.setAttribute('href', 'https://kumpuni.netlify.app/terms');
    return () => {
      document.title = 'Kumpuni — DIY Home Maintenance Guide';
      if (canonical) canonical.setAttribute('href', 'https://kumpuni.netlify.app/');
    };
  }, []);

  return (
    <div className="min-h-screen bg-[#F7F7F5] text-[#1F2937]">
      <div className="max-w-3xl mx-auto px-6 py-16">
        {/* Back */}
        <a
          href="/"
          className="inline-flex items-center gap-2 text-sm text-[#9CA3AF] hover:text-[#6DBE75] transition-colors mb-10"
        >
          <ChevronLeft size={16} />
          Back to Kumpuni
        </a>

        {/* Header */}
        <div className="mb-12">
          <div className="flex items-center gap-3 mb-6">
            <img src="/logo.png" alt="Kumpuni" className="w-10 h-10 rounded-xl" />
            <span className="text-xl font-bold">Kumpuni</span>
          </div>
          <h1 className="text-4xl font-extrabold tracking-tight mb-3">Terms of Service</h1>
          <p className="text-[#9CA3AF] text-sm">Last updated: April 19, 2026</p>
        </div>

        {/* Divider */}
        <div className="h-px bg-[#E5E7EB] mb-12" />

        {/* Content */}
        <div className="prose max-w-none space-y-10 text-[#6B7280] leading-relaxed">

          <section>
            <h2 className="text-xl font-bold text-[#1F2937] mb-3">1. Acceptance of Terms</h2>
            <p>
              By downloading, installing, or using Kumpuni ("the App"), you agree to be bound by
              these Terms of Service. If you do not agree with any part of these terms, you must not
              use the App.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1F2937] mb-3">2. License</h2>
            <p>
              Kumpuni grants you a personal, non-exclusive, non-transferable, limited license to
              install and use the App on devices you own or control. This license is for personal,
              non-commercial use only. You may not:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-3">
              <li>Copy, modify, or distribute the App or any portion of it</li>
              <li>Reverse engineer, decompile, or disassemble the App</li>
              <li>Rent, lease, or lend the App to third parties</li>
              <li>Use the App for any unlawful purpose</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1F2937] mb-3">3. Free to Use</h2>
            <p>
              Kumpuni is free to download and use. Basic DIY guides, the AI assistant,
              and fixer discovery features are available at no cost. Optional premium
              features or future subscriptions may be introduced with clear notice.
            </p>
            <p className="mt-3">
              Any in-app purchases or subscriptions are processed by the Apple App Store
              or Google Play Store. Kumpuni does not directly handle payment information.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1F2937] mb-3">4. AI Assistant</h2>
            <p>
              The AI assistant provides general home maintenance guidance and suggestions.
              Responses are generated by AI models and may not always be 100% accurate or
              complete. Always use your own judgment and consult a professional for
              complex or dangerous repairs (e.g., electrical, gas, structural work).
            </p>
            <p className="mt-3">
              Kumpuni does not warrant the accuracy of any AI-generated advice and is not
              liable for any damage or injury resulting from following such guidance.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1F2937] mb-3">5. Fixer Services</h2>
            <p>
              Kumpuni connects homeowners with independent service providers ("Fixers").
              We do not employ, endorse, or guarantee the quality of any Fixer. All
              arrangements, payments, and disputes between you and a Fixer are solely
              between you and that Fixer.
            </p>
            <p className="mt-3">
              By posting a job, you agree that Kumpuni is only a platform for discovery
              and is not responsible for the actions, pricing, or outcomes of any Fixer.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1F2937] mb-3">6. Safety Disclaimer</h2>
            <p>
              Home repairs can involve risks including electrical shock, falls, cuts,
              and exposure to hazardous materials. Kumpuni guides and AI advice are for
              informational purposes only. If you are unsure about a repair, stop and
              consult a licensed professional.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1F2937] mb-3">7. Acceptable Use</h2>
            <p>You agree not to use Kumpuni to:</p>
            <ul className="list-disc pl-6 space-y-2 mt-3">
              <li>Post jobs or content that is illegal, harmful, or defamatory</li>
              <li>Misrepresent yourself or a repair job to Fixers</li>
              <li>Violate any applicable local, national, or international laws</li>
              <li>Infringe upon the intellectual property rights of others</li>
              <li>Use the app for commercial purposes without authorization</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1F2937] mb-3">8. Disclaimer of Warranties</h2>
            <p>
              The App is provided "as is" without warranty of any kind, express or implied,
              including but not limited to warranties of merchantability, fitness for a particular
              purpose, or non-infringement. Kumpuni does not guarantee uninterrupted or error-free
              operation of the App.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1F2937] mb-3">9. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, Kumpuni and its developer shall not be liable
              for any indirect, incidental, special, consequential, or punitive damages, including
              loss of data or profits, arising from your use of or inability to use the App.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1F2937] mb-3">10. Updates &amp; Changes</h2>
            <p>
              We reserve the right to modify these Terms of Service at any time. Updated terms
              will be posted on this page with a revised date. Continued use of the App after
              changes constitutes your acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1F2937] mb-3">11. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with applicable law.
              Any disputes shall be resolved through the appropriate legal channels in the
              jurisdiction of the developer.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1F2937] mb-3">12. Contact</h2>
            <p>For questions about these Terms, contact:</p>
            <div className="mt-3 bg-white border border-[#E5E7EB] rounded-2xl p-5 shadow-sm">
              <p className="font-semibold text-[#1F2937]">Richmond Constante</p>
              <p className="text-sm text-[#9CA3AF] mt-1">
                Portfolio:{' '}
                <a href="https://rcconstante.dev" className="text-[#6DBE75] hover:underline" target="_blank" rel="noopener noreferrer">
                  rcconstante.dev
                </a>
              </p>
              <p className="text-sm text-[#9CA3AF] mt-1">
                GitHub:{' '}
                <a href="https://github.com/rcconstante" className="text-[#6DBE75] hover:underline" target="_blank" rel="noopener noreferrer">
                  github.com/rcconstante
                </a>
              </p>
            </div>
          </section>
        </div>

        {/* Divider */}
        <div className="h-px bg-[#E5E7EB] mt-16 mb-8" />

        {/* Footer mini */}
        <div className="flex items-center justify-between text-xs text-[#9CA3AF]">
          <span>© 2026 Kumpuni</span>
          <a href="/privacy" className="hover:text-[#6DBE75] transition-colors">Privacy Policy</a>
        </div>
      </div>
    </div>
  );
}
